# Generated by Django 5.0 on 2023-12-22 14:34

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maLoai', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='L', unique=True)),
                ('tenLoai', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'LoaiSPs',
            },
        ),
        migrations.CreateModel(
            name='DiaChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaChi', models.CharField(max_length=100, null=True)),
                ('trangThai', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DiaChis',
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giaBan', models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999)),
                ('trangThaiThanhToan', models.BooleanField(default=False)),
                ('ngayDatHang', models.DateTimeField(auto_now_add=True)),
                ('trangThaiSP', models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý')], default='processing', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'GioHangs',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNCC', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='KH', unique=True)),
                ('tenNCC', models.CharField(max_length=100)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('diaChi', models.CharField(default='123 Main Street.', max_length=100)),
                ('lienHe', models.CharField(default='+123 (456) 789', max_length=100)),
                ('tGPhanHoi', models.CharField(default='100', max_length=100)),
                ('tGVanChuyen', models.CharField(default='100', max_length=100)),
                ('danhGia', models.CharField(default='100', max_length=100)),
                ('ngayQuayLai', models.CharField(default='100', max_length=100)),
                ('thoiHanBaoHanh', models.CharField(default='100', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'NhaCungCaps',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maSP', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='SP', unique=True)),
                ('tenSP', models.CharField(max_length=100)),
                ('anhSP', models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('giaBan', models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999)),
                ('giaCu', models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999)),
                ('trangThaiSP', models.CharField(choices=[('in_revie', 'Xem xét'), ('draft', 'Bản nháp'), ('rejected', 'Từ chối'), ('published', 'Công khai'), ('disabled', 'Xóa')], default='in_revie', max_length=10)),
                ('sanCo', models.BooleanField(default=True)),
                ('loaiSP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loaisp')),
                ('nhaCungCap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='core.nhacungcap')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SanPhams',
            },
        ),
        migrations.CreateModel(
            name='DanhSachDatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayDH', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sanPham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sanpham')),
            ],
            options={
                'verbose_name_plural': 'DanhSachDatHangs',
            },
        ),
        migrations.CreateModel(
            name='DanhGiaSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danhGia', models.TextField()),
                ('xepHang', models.IntegerField(choices=[(2, '★★☆☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆')], default=None)),
                ('ngayDG', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sanPham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.sanpham')),
            ],
            options={
                'verbose_name_plural': 'DanhGiaSPs',
            },
        ),
        migrations.CreateModel(
            name='SP_GH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangThaiSP', models.CharField(max_length=100)),
                ('sanPham', models.CharField(max_length=100)),
                ('anhSP', models.CharField(max_length=100)),
                ('soLuong', models.IntegerField(default=0)),
                ('giaBan', models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999)),
                ('thanhTien', models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999)),
                ('gioHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giohang')),
            ],
            options={
                'verbose_name_plural': 'SP_GHs',
            },
        ),
    ]
