# Generated by Django 5.0 on 2023-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (5, '★★★★★'), (1, '★☆☆☆☆'), (3, '★★★☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('rejected', 'Từ chối'), ('published', 'Công khai'), ('disabled', 'Xóa'), ('draft', 'Bản nháp'), ('in_revie', 'Xem xét')], default='in_revie', max_length=10),
        ),
    ]
