# Generated by Django 5.0 on 2023-12-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_danhgiasp_xephang_alter_giohang_trangthaisp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (5, '★★★★★'), (3, '★★★☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('process', 'Đang xử lý'), ('shipped', 'Đang vận chuyển'), ('delivered', 'Đang giao hàng')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('rejected', 'Từ chối'), ('published', 'Công khai'), ('in_revie', 'Xem xét'), ('disabled', 'Xóa'), ('draft', 'Bản nháp')], default='in_revie', max_length=10),
        ),
    ]
