# Generated by Django 5.0 on 2023-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_danhgiasp_xephang_alter_giohang_trangthaisp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (1, '★☆☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('published', 'Công khai'), ('disabled', 'Xóa'), ('rejected', 'Từ chối'), ('in_revie', 'Xem xét'), ('draft', 'Bản nháp')], default='in_revie', max_length=10),
        ),
    ]
