# Generated by Django 5.0 on 2023-12-23 03:20

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_danhgiasp_xephang_alter_sanpham_trangthaisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('rejected', 'Từ chối'), ('in_revie', 'Xem xét'), ('published', 'Công khai'), ('draft', 'Bản nháp'), ('disabled', 'Xóa')], default='in_revie', max_length=10),
        ),
        migrations.CreateModel(
            name='ThongTinSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maTT', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='TT', unique=True)),
                ('tenThuongHieu', models.CharField(max_length=100)),
                ('chatLieu', models.CharField(max_length=100)),
                ('kieuDang', models.CharField(max_length=100)),
                ('tgBaoHanh', models.CharField(default='6', max_length=100)),
                ('sanPham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sanpham')),
            ],
            options={
                'verbose_name_plural': 'ThongTinSPs',
            },
        ),
    ]
