# Generated by Django 5.0 on 2023-12-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_danhgiasp_xephang_alter_giohang_trangthaisp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (5, '★★★★★'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('disabled', 'Xóa'), ('rejected', 'Từ chối'), ('draft', 'Bản nháp'), ('in_revie', 'Xem xét'), ('published', 'Công khai')], default='in_revie', max_length=10),
        ),
    ]
