# Generated by Django 5.0 on 2023-12-23 09:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_danhgiasp_xephang_alter_sanpham_trangthaisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(4, '★★★★☆'), (3, '★★★☆☆'), (2, '★★☆☆☆'), (5, '★★★★★'), (1, '★☆☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='moTa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='moTa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('published', 'Công khai'), ('in_revie', 'Xem xét'), ('draft', 'Bản nháp'), ('rejected', 'Từ chối'), ('disabled', 'Xóa')], default='in_revie', max_length=10),
        ),
    ]
