# Generated by Django 5.0 on 2023-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_danhgiasp_xephang_alter_giohang_trangthaisp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(5, '★★★★★'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (2, '★★☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('in_revie', 'Xem xét'), ('disabled', 'Xóa'), ('rejected', 'Từ chối'), ('published', 'Công khai'), ('draft', 'Bản nháp')], default='in_revie', max_length=10),
        ),
    ]
