# Generated by Django 5.0 on 2023-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_danhsachdathang_trangthaidh_alter_danhgiasp_xephang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachdathang',
            name='trangThaiThanhToan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('process', 'Đang xử lý'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('disabled', 'Xóa'), ('in_revie', 'Xem xét'), ('published', 'Công khai'), ('rejected', 'Từ chối'), ('draft', 'Bản nháp')], default='in_revie', max_length=10),
        ),
    ]
