# Generated by Django 5.0 on 2023-12-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_danhgiasp_xephang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachdathang',
            name='giaBan',
            field=models.DecimalField(decimal_places=0, default='10000', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (1, '★☆☆☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('rejected', 'Từ chối'), ('in_revie', 'Xem xét'), ('published', 'Công khai'), ('disabled', 'Xóa')], default='in_revie', max_length=10),
        ),
    ]
