# Generated by Django 5.0 on 2023-12-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_danhsachdathang_giaban_alter_danhgiasp_xephang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (5, '★★★★★'), (1, '★☆☆☆☆'), (4, '★★★★☆'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Công khai'), ('rejected', 'Từ chối'), ('in_revie', 'Xem xét'), ('disabled', 'Xóa')], default='in_revie', max_length=10),
        ),
    ]
