# Generated by Django 5.0 on 2023-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_danhgiasp_xephang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhsachdathang',
            name='sanPham',
        ),
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(3, '★★★☆☆'), (5, '★★★★★'), (4, '★★★★☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('process', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('disabled', 'Xóa'), ('published', 'Công khai'), ('rejected', 'Từ chối'), ('in_revie', 'Xem xét')], default='in_revie', max_length=10),
        ),
    ]
