# Generated by Django 5.0 on 2023-12-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_danhsachdathang_sanpham_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (3, '★★★☆☆'), (5, '★★★★★'), (1, '★☆☆☆☆'), (4, '★★★★☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('processing', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('shipped', 'Đang vận chuyển'), ('processing', 'Đang xử lý'), ('delivered', 'Đang giao hàng')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('published', 'Công khai'), ('disabled', 'Xóa'), ('rejected', 'Từ chối'), ('draft', 'Bản nháp'), ('in_revie', 'Xem xét')], default='in_revie', max_length=10),
        ),
    ]
