# Generated by Django 5.0 on 2023-12-24 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_danhgiasp_xephang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgiasp',
            name='xepHang',
            field=models.IntegerField(choices=[(2, '★★☆☆☆'), (4, '★★★★☆'), (5, '★★★★★'), (1, '★☆☆☆☆'), (3, '★★★☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='danhsachdathang',
            name='trangThaiDH',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='trangThaiSP',
            field=models.CharField(choices=[('processing', 'Đang xử lý'), ('delivered', 'Đang giao hàng'), ('shipped', 'Đang vận chuyển')], default='processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trangThaiSP',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('rejected', 'Từ chối'), ('in_revie', 'Xem xét'), ('disabled', 'Xóa'), ('published', 'Công khai')], default='in_revie', max_length=10),
        ),
        migrations.CreateModel(
            name='DanhSachYeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThem', models.DateTimeField(auto_now_add=True)),
                ('sanPham', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sanpham')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'DanhSachYeuThichs',
            },
        ),
    ]
